#指向mapper的xml文件
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml



spring:
#  datasource:
#    url: jdbc:mysql://192.168.83.139:3306/activiti_cstm?useUnicode=true&characterEncoding=utf8
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
  activiti:
    database-schema-update: false #每次应用启动不检查Activiti数据表是否存在及版本号是否匹配，提升应用启动速度
    check-process-definitions: false #关闭activiti自动部署扫描
    datasource:
      url: jdbc:mysql://192.168.83.139:3306/activiti_cstm?useUnicode=true&characterEncoding=utf8
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: root

#      type: com.zaxxer.hikari.HikariDataSource
#      hikari:
#        maximum-pool-size: 30
#        idle-timeout: 30000
#        connection-test-query: select 1 from DUAL
#        auto-commit: true
#        minimum-idle: 5
#        connection-timeout: 30000
#        pool-name: activiti-datasource-pool
